# Generated by Django 2.0 on 2017-12-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(verbose_name='预定日期')),
                ('book_time', models.IntegerField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00')], verbose_name='预定时间')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='会议室名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='meetingroom',
            field=models.ForeignKey(on_delete=True, to='app01.MeetingRoom', verbose_name='会议室'),
        ),
        migrations.AddField(
            model_name='book',
            name='userinfo',
            field=models.ForeignKey(on_delete=True, to='app01.UserInfo', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_date', 'book_time', 'meetingroom')},
        ),
    ]
